<!DOCTYPE issuelist [
<!ELEMENT issuelist (listversion,os*,headerfile*,library*)>

<!ELEMENT listversion (#PCDATA)>

<!ELEMENT os (osversion,buildweek)>
<!ELEMENT osversion (#PCDATA)>
<!ELEMENT buildweek (#PCDATA)>

<!ELEMENT headerfile (version+)>
<!ATTLIST headerfile
			name CDATA #REQUIRED>
<!ELEMENT version (status,comment)>
<!ATTLIST version
			checksum CDATA #REQUIRED>

<!ELEMENT library (issue+)>
<!ATTLIST library
			name CDATA #REQUIRED>
<!ELEMENT issue (typeid,funcname?,newfuncname?,funcpos?,newfuncpos?,status,comment)>
<!ELEMENT typeid (#PCDATA)>
<!ELEMENT funcname (#PCDATA)>
<!ELEMENT newfuncname (#PCDATA)>
<!ELEMENT funcpos (#PCDATA)>
<!ELEMENT newfuncpos (#PCDATA)>

<!ELEMENT status (#PCDATA)>
<!ELEMENT comment (#PCDATA)>
]>

<!--
- Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
- All rights reserved.
- This component and the accompanying materials are made available
- under the terms of the License "Eclipse Public License v1.0"
- which accompanies this distribution, and is available
- at the URL "http://www.eclipse.org/legal/epl-v10.html".
- 
- Initial Contributors:
- Nokia Corporation - initial contribution.
- 
- Contributors:
- 
- Description:
- 
-->

<issuelist>
  <listversion>2008-04-30</listversion>

  <headerfile name="hatc012a.h">
    <version checksum="Iivrfk2Bny59t"
      <status>OK</status>
      <comment>The changes do not cause breaks.</comment>
    </version>
  </headerfile>

  <headerfile name="hatc012b.h">
    <version checksum="K5PpQQVCHibvM">
      <status>OK</status>
      <comment>The changes do not cause breaks.</comment>
    </version>
  </headerfile>

</issuelist>
