<!DOCTYPE issuelist [
<!ELEMENT issuelist (listversion,os*,headerfile*,library*)>

<!ELEMENT listversion (#PCDATA)>

<!ELEMENT os (osversion,buildweek)>
<!ELEMENT osversion (#PCDATA)>
<!ELEMENT buildweek (#PCDATA)>

<!ELEMENT headerfile (version+)>
<!ATTLIST headerfile
			name CDATA #REQUIRED>
<!ELEMENT version (status,comment)>
<!ATTLIST version
			checksum CDATA #REQUIRED>

<!ELEMENT library (issue+)>
<!ATTLIST library
			name CDATA #REQUIRED>
<!ELEMENT issue (typeid,funcname?,newfuncname?,funcpos?,newfuncpos?,status,comment)>
<!ELEMENT typeid (#PCDATA)>
<!ELEMENT funcname (#PCDATA)>
<!ELEMENT newfuncname (#PCDATA)>
<!ELEMENT funcpos (#PCDATA)>
<!ELEMENT newfuncpos (#PCDATA)>

<!ELEMENT status (#PCDATA)>
<!ELEMENT comment (#PCDATA)>
]>

<!--
- Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
- All rights reserved.
- This component and the accompanying materials are made available
- under the terms of the License "Eclipse Public License v1.0"
- which accompanies this distribution, and is available
- at the URL "http://www.eclipse.org/legal/epl-v10.html".
- 
- Initial Contributors:
- Nokia Corporation - initial contribution.
- 
- Contributors:
- 
- Description:
- 
-->

<issuelist>
  <listversion>2008-07-11</listversion>
	<os><osversion>3.0</osversion><buildweek>2007wk07</buildweek></os>
	<os><osversion>3.1</osversion><buildweek>2008wk07</buildweek></os>
	<os><osversion>3.2</osversion><buildweek>2008wk26</buildweek></os>
	<os><osversion>5.0</osversion><buildweek>2008wk26</buildweek></os>

  <headerfile name="agentdialog.h">
    <version checksum="*******AaopJx">
      <status>OK</status>
      <comment>This breaks compatibility, but both class and file are marked @internalTechnology and should not be used by third parties.</comment>
    </version>
  </headerfile>

  <headerfile name="aknappui.h">
    <version checksum="beh07ATCbPbTg">
      <status>OK</status>
      <comment>1) Enumerations and BaseConstructL()'s default param have been changed keeping binary compatibility in mind; depending on the input values (enum or param) used by an application, S60 can determine if the application is aware of the middle softkey or not. 2) The name of SetLocalUiZoomL() has been changed to SetLocalUiZoom(). This is ok from BC point of view. 3) The virtual table has changed in CCoeAppUi, and is shown here as well. The change is ok, see coeaui.h for more information.</comment>
    </version>
    <version checksum="P8rAG-hDAflx7">
      <status>OK</status>
      <comment>1) The name of SetLocalUiZoomL() has been changed to SetLocalUiZoom(). This is ok from BC point of view. 2) The virtual table has changed in CCoeAppUi, and is shown here as well. The change is ok, see coeaui.h for more information.</comment>
    </version>
    <version checksum="Y1xBFapDAflx7">
      <status>OK</status>
      <comment>1) The name of SetLocalUiZoomL() has been changed to SetLocalUiZoom(). This is ok from BC point of view. 2) The virtual table has changed in CCoeAppUi, and is shown here as well. The change is ok, see coeaui.h for more information.</comment>
    </version>
    <version checksum="cgrMqv4DAflx7">
      <status>OK</status>
      <comment>1) The name of SetLocalUiZoomL() has been changed to SetLocalUiZoom(). This is ok from BC point of view. 2) The virtual table has changed in CCoeAppUi, and is shown here as well. The change is ok, see coeaui.h for more information.</comment>
    </version>
  </headerfile>

  <headerfile name="akncheckboxsettingpage.h">
    <version checksum="OWci+NoDEnmh8">
      <status>OK</status>
      <comment>This overridden function will not be called in applications, which derive from this class and are built with the SDK. Generally, this may cause unexpected behaviour. However, the effects of this particular change have been studied and approved.</comment>
    </version>
  </headerfile>

  <headerfile name="aknclearer.h">
    <version checksum="-bqb7sODGTJll">
      <status>OK</status>
      <comment>This overridden function will not be called in applications, which derive from this class and are built with the SDK. Generally, this may cause unexpected behaviour. However, the effects of this particular change have been studied and approved.</comment>
    </version>
  </headerfile>
  
    <headerfile name="domain\middleware\downloadmgrclientapiext.h">
    <version checksum="-SBIvHDiA2c321">
      <status>OK</status>
      <comment>File has compilation issues and cannot find DownloadMgrClient.h</comment>
    </version>
  </headerfile>
  
	<headerfile name="akneditstateindicator.h">
    <version checksum="+7KNxQUC8dWTn">
      <status>NOK</status>
      <comment>Enum values added to the middle of enum TAknEditingState because of which the value of EDevanagariIndicNumeric has changed in TAknEditingState.</comment>
    </version>
  </headerfile>
	
  <headerfile name="akngrid.h">
    <version checksum="+ckDXAkDrcxXC">
      <status>OK</status>
      <comment>The removed data member is not used in any inline functions.</comment>
    </version>
    <version checksum="DCh2DNWBOffau">
      <status>NOK</status>
      <comment>This overridden function will not be called in applications, which derive from this class and are built with the SDK. Generally, this may cause unexpected behaviour.</comment>
    </version>
    <version checksum="DA3Z-T4BOffau">
      <status>OK</status>
      <comment>ignored issue.</comment>
    </version>
  </headerfile>
  
  <headerfile name="babackup.h">
    <version checksum="b4wS9q-BRxrqr">
      <status>OK</status>
      <comment>It's commented that CBaBackupSessionWrapper::CloseServer( ) should not be used.</comment>
    </version>
     </headerfile>

   <headerfile name="middleware\akngrid.h">
    <version checksum="DCh2DNWBOffau">
      <status>NOK</status>
      <comment>This overridden function will not be called in applications, which derive from this class and are built with the SDK. Generally, this may cause unexpected behaviour.</comment>
    </version>
    <version checksum="CWr04KWBOffau">
      <status>OK</status>
      <comment>ignored BC-break.</comment>
    </version>
  </headerfile>

  <headerfile name="aknlistquerycontrol.h">
    <version checksum="tF6CYqNDnz6Jh">
      <status>OK</status>
      <comment>The changed data member iSpare is not used by an inline functions.</comment>
    </version>
  </headerfile>

  <headerfile name="aknlistquerydialog.h">
    <version checksum="*******Ahu6S2">
      <status>OK</status>
      <comment>This overridden function will not be called in applications, which derive from this class and are built with the SDK. Generally, this may cause unexpected behaviour. However, the effects of this particular change have been studied and approved.</comment>
    </version>
  </headerfile>

  <headerfile name="aknmessagequerycontrol.h">
    <version checksum="1NXomtIBe7mhN">
      <status>OK</status>
      <comment>Private data member iSpare is not used in any inline functions (or in any other way for that matter), so it's ok to replace it.</comment>
    </version>
    <version checksum="*******CW6Yiy">
      <status>OK</status>
      <comment>The only data member used in an inline function is iNumberOfLines. The offset of this data member has not changed, so ok.</comment>
    </version>
    <version checksum="*******A29o2i">
      <status>OK</status>
      <comment>The only data member used in an inline function is iNumberOfLines. The offset of this data member has not changed, so ok.</comment>
    </version>
    <version checksum="5ATmXWUB2a2mi">
      <status>OK</status>
      <comment>The only data member used in an inline function is iNumberOfLines. The offset of this data member has not changed, so ok.</comment>
    </version>
    <version checksum="5ATmXWUCYQkjO">
      <status>OK</status>
      <comment>The only data member used in an inline function is iNumberOfLines. The offset of this data member has not changed, so ok.</comment>
    </version>
    <version checksum="8lXP5wPCYQkjO">
      <status>OK</status>
      <comment>The only data member used in an inline function is iNumberOfLines. The offset of this data member has not changed, so ok.</comment>
    </version>
  </headerfile>
  
 	<headerfile name="middleware\aknmessagequerycontrol.h">
    <version checksum="5ATmXWUCYQkjO">
      <status>OK</status>
      <comment>The only data member used in an inline function is iNumberOfLines. The offset of this data member has not changed, so ok.</comment>
    </version>
    <version checksum="8lXP5wPCYQkjO">
      <status>OK</status>
      <comment>The only data member used in an inline function is iNumberOfLines. The offset of this data member has not changed, so ok.</comment>
    </version>
     <version checksum="D7TIJO2AsEPr5">
      <status>NOK</status>
      <comment>1.Class is NONSHARABLE, so adding a virtual function won't break BC. 2.iNumberOfLines changed its offset although used in inline function, it constitutes a break.</comment>
    </version>
     <version checksum="GcUpzDeCFnzlJ">
      <status>OK</status>
      <comment>The only data member used in an inline function is iNumberOfLines. The offset of this data member has not changed, so ok.</comment>
    </version>
  </headerfile>

  <headerfile name="aknmultilinequerycontrol.h">
    <version checksum="cxNPr+zD8AKmE">
      <status>OK</status>
      <comment>This overridden function will not be called in applications, which derive from this class and are built with the SDK. Generally, this may cause unexpected behaviour. However, the effects of this particular change have been studied and approved.</comment>
    </version>
  </headerfile>

	<headerfile name="aknnavi.h">
    <version checksum="kOMGn9UDH-IWE">
      <status>OK</status>
      <comment>Include guard macro name changed, which is OK.</comment>
    </version>
  </headerfile>
  
  <headerfile name="aknnavide.h">
    <version checksum="TffYin0DnxoFY">
      <status>OK</status>
      <comment>This overridden function will not be called in applications, which derive from this class and are built with the SDK. Generally, this may cause unexpected behaviour. However, the effects of this particular change have been studied and approved.</comment>
    </version>
    <version checksum="OrnGCL9Ahu6S2">
      <status>OK</status>
      <comment>This overridden function will not be called in applications, which derive from this class and are built with the SDK. Generally, this may cause unexpected behaviour. However, the effects of this particular change have been studied and approved.</comment>
    </version>
    <version checksum="fQqIYeSDnxoFY">
      <status>OK</status>
      <comment>This overridden function will not be called in applications, which derive from this class and are built with the SDK. Generally, this may cause unexpected behaviour. However, the effects of this particular change have been studied and approved.</comment>
    </version>
    <version checksum="fbYpYrWBJADQX">
      <status>OK</status>
      <comment>Include guard macro name changed, which is OK.</comment>
    </version>
    <version checksum="jT7GYtwBJADQX">
      <status>OK</status>
      <comment>Include guard macro name changed, which is OK.</comment>
    </version>
    <version checksum="rg4CgsDBJADQX">
      <status>OK</status>
      <comment>Include guard macro name changed, which is OK.</comment>
    </version>
  </headerfile>

	<headerfile name="aknnotecontrol.h">
    <version checksum="HBxNZGGCSEM6B">
      <status>OK</status>
      <comment>This overridden function will not be called in applications, which derive from this class and are built with the SDK. Generally, this may cause unexpected behaviour.</comment>
    </version>
  </headerfile>
  
  <headerfile name="aknnotifystd.h">
    <version checksum="D-1xugsBA7hej">
      <status>OK</status>
      <comment>Struct SAknBatteryNotifyParams is marked @internal</comment>
    </version>
  </headerfile>
  
  <headerfile name="middleware\aknnotifystd.h">
    <version checksum="D-1xugsBA7hej">
      <status>OK</status>
      <comment>Struct SAknBatteryNotifyParams is marked @internal</comment>
    </version>
  </headerfile>
  
  <headerfile name="aknpopupheadingpane.h">
    <version checksum="EXmNKPtA8zo-d">
      <status>OK</status>
      <comment>This overridden function will not be called in applications, which derive from this class and are built with the SDK. Generally, this may cause unexpected behaviour. However, the effects of this particular change have been studied and approved.</comment>
    </version>
  </headerfile>

  <headerfile name="aknpopupnotify.h">
    <version checksum="aHFPoVyBy6XXN">
      <status>OK</status>
      <comment>File inclusion macro has changed, which is ok.</comment>
    </version>
  </headerfile>

  <headerfile name="aknpopupsettingpage.h">
    <version checksum="eo59m48C6wYyh">
      <status>OK</status>
      <comment>This overridden function will not be called in applications, which derive from this class and are built with the SDK. Generally, this may cause unexpected behaviour. However, the effects of this particular change have been studied and approved.</comment>
    </version>
  </headerfile>

  <headerfile name="aknquerycontrol.h">
    <version checksum="aR1xtTnAZp+aU">
      <status>OK</status>
      <comment>1) This overridden function will not be called in applications, which derive from this class and are built with the SDK. Generally, this may cause unexpected behaviour. However, the effects of this particular change have been studied and approved. 2) Private data member iSpare is not used in any inline functions (or in any other way for that matter), so it's ok to replace it.</comment>
    </version>
    <version checksum="XTvPG4jAHaclx">
      <status>OK</status>
      <comment>Private data member iSpare is not used in any inline functions (or in any other way for that matter), so it's ok to replace it.</comment>
    </version>
  </headerfile>
  
   <headerfile name="middleware\aknquerydialog.h">
    <version checksum="ftKNtwtBjJUuZ">
      <status>NOK</status>
      <comment>Virtual functions overrideen in deliverable class. Will not be called in clients deriving from this class</comment>
    </version>
  </headerfile>
  
  <headerfile name="aknradiobuttonsettingpage.h">
    <version checksum="xUwYmnKBEzSL4">
      <status>OK</status>
      <comment>This overridden function will not be called in applications, which derive from this class and are built with the SDK. Generally, this may cause unexpected behaviour. However, the effects of this particular change have been studied and approved.</comment>
    </version>
  </headerfile>

	<headerfile name="aknsconstants.hrh">
    <version checksum="o0yoK2MChv9Aq">
      <status>OK</status>
      <comment>Enum values added without changing any of the existing enum values.</comment>
    </version>
    <version checksum="8A7CQzEChv9Aq">
      <status>OK</status>
      <comment>Enum values added without changing any of the existing enum values.</comment>
    </version>
    <version checksum="0155tuSChv9Aq">
      <status>OK</status>
      <comment>Enum values added without changing any of the existing enum values.</comment>
    </version>
    <version checksum="25Fe53BChv9Aq">
      <status>OK</status>
      <comment>Enum values added without changing any of the existing enum values.</comment>
    </version>
    <version checksum="flMwFF-Chv9Aq">
      <status>OK</status>
      <comment>Enum values added without changing any of the existing enum values.</comment>
    </version>
    <version checksum="flMwFF-Chv9Aq">
      <status>OK</status>
      <comment>Enum values added without changing any of the existing enum values.</comment>
    </version>
    <version checksum="IdcDcyuChv9Aq">
      <status>OK</status>
      <comment>Enum values added without changing any of the existing enum values.</comment>
    </version>
    <version checksum="cxeqsI7Chv9Aq">
      <status>OK</status>
      <comment>Enum values added without changing any of the existing enum values.</comment>
    </version>
     <version checksum="EMu33UcChv9Aq">
      <status>OK</status>
      <comment>Enum values added without changing any of the existing enum values.</comment>
    </version>
    <version checksum="3L5Op3zChv9Aq">
      <status>OK</status>
      <comment>Enum values added without changing any of the existing enum values.</comment>
    </version>
    <version checksum="hyqaQM7Chv9Aq">
      <status>OK</status>
      <comment>Enum values added without changing any of the existing enum values.</comment>
    </version>
	</headerfile>
	
	 <headerfile name="middleware\aknPopupHeadingPane.h">
    <version checksum="RWWnVfsAXbN44">
      <status>NOK</status>
      <comment>CAknPopupHeadingPane is publised class, so changing the size of class is not allowed since constructor is a public member and thus it is derivable.</comment>
    </version>
   </headerfile>

	<headerfile name="middleware\aknsconstants.hrh">
    <version checksum="IdcDcyuChv9Aq">
      <status>OK</status>
      <comment>Enum values added without changing any of the existing enum values.</comment>
    </version>
    <version checksum="88goBx8Chv9Aq">
      <status>OK</status>
      <comment>Enum values added without changing any of the existing enum values.</comment>
    </version>
    <version checksum="cxeqsI7Chv9Aq">
      <status>OK</status>
      <comment>Enum values added without changing any of the existing enum values.</comment>
    </version>
    <version checksum="IPKfCxcChv9Aq">
      <status>OK</status>
      <comment>Enum values added without changing any of the existing enum values.</comment>
    </version>
    <version checksum="EMu33UcChv9Aq">
      <status>OK</status>
      <comment>Enum values added without changing any of the existing enum values.</comment>
    </version>
    <version checksum="OEsMflbChv9Aq">
      <status>OK</status>
      <comment>Enum values added without changing any of the existing enum values.</comment>
    </version>
    <version checksum="cwbO4hVChv9Aq">
      <status>OK</status>
      <comment>Only the enum indicating the max value has changed.</comment>
    </version>
    <version checksum="3L5Op3zChv9Aq">
      <status>OK</status>
      <comment>Only the enum indicating the max value has changed.</comment>
    </version>
    <version checksum="9UTg2VMChv9Aq">
      <status>OK</status>
      <comment>Only the enum indicating the max value has changed.</comment>
    </version>
    <version checksum="qJvl0tqChv9Aq">
      <status>OK</status>
      <comment>Only the enum indicating the max value has changed.</comment>
    </version>
     <version checksum="I-Y8-plChv9Aq">
      <status>OK</status>
      <comment>Only the enum indicating the max value has changed.</comment>
    </version>
    <version checksum="eSzryquChv9Aq">
      <status>OK</status>
      <comment>Only the enum indicating the max value has changed.</comment>
    </version>
    <version checksum="rHFrlSbChv9Aq">
      <status>OK</status>
      <comment>Only the enum indicating the max value has changed.</comment>
    </version>
	<version checksum="CFvxeSqChv9Aq">
      <status>OK</status>
      <comment>Only the enum indicating the max value has changed.</comment>
    </version>
  </headerfile>

  <headerfile name="aknsitemid.h">
    <version checksum="KmvmgS0BVVnyJ">
      <status>OK</status>
      <comment>Removed enum is @internal, which is OK.</comment>
    </version>
  </headerfile>
  
  <headerfile name="middleware\aknslider.h">
    <version checksum="ZBebrmgBLETXU">
      <status>OK</status>
      <comment>Enum values are not removed.A name has been given to a nameless enumeration.</comment>
    </version>
    <version checksum="areK9PMBLETXU">
      <status>OK</status>
      <comment>Enum values are not removed.A name has been given to a nameless enumeration.</comment>
    </version>
    <version checksum="cnMw79uBLETXU">
      <status>OK</status>
      <comment>Enum values are not removed.A name has been given to a nameless enumeration.</comment>
    </version>
	<version checksum="hOmFSPDBLETXU">
      <status>OK</status>
      <comment>Enum values are not removed.A name has been given to a nameless enumeration.</comment>
    </version>
  </headerfile>

  <headerfile name="aknsskininstance.h">
    <version checksum="*******CRglHB">
      <status>OK</status>
      <comment>Virtual function added to interface. Ok as interface not supposed to be derived from by third parties.</comment>
    </version>
    <version checksum="*******CHFcRj">
      <status>OK</status>
      <comment>Virtual function added to interface. Ok as interface not supposed to be derived from by third parties.</comment>
    </version>
  </headerfile>

  <headerfile name="middleware\aknsskininstance.h">
    <version checksum="KYPSjfbAjrtga">
      <status>OK</status>
      <comment>Virtual function added to interface. Ok as interface not supposed to be derived from by third parties.</comment>
    </version>
  </headerfile>

  <headerfile name="akntextdecorationmetrics.h">
    <version checksum="bOi+RoNA2c321">
      <status>OK</status>
      <comment>Headers compatible. Compilation error can be fixed by including AknFontCategory.h.</comment>
    </version>
  </headerfile>

  <headerfile name="akntextsettingpage.h">
    <version checksum="lvzMI+NBFFunm">
      <status>NOK</status>
      <comment>1) Class size has changed due to the addition of iMultitapWaitTimer, and class has exported constructor. So this is a BC break and must be fixed. 2) These overridden functions will not be called in applications, which derive from this class and are built with the SDK. Generally, this may cause unexpected behaviour. However, the effects of this particular change have been studied and approved. So the overridden virtual functions are OK.</comment>
    </version>
    <version checksum="XXpb5RfBfUN+7">
      <status>OK</status>
      <comment>These overridden functions will not be called in applications, which derive from this class and are built with the SDK. Generally, this may cause unexpected behaviour. However, the effects of this particular change have been studied and approved. So the overridden virtual functions are OK.</comment>
    </version>
  </headerfile>

  <headerfile name="akntitle.h">
    <version checksum="*******A2xt0c">
      <status>OK</status>
      <comment>Include guard macro name changed from C_AKNTITLE_H --> OK</comment>
    </version>
  </headerfile>

  <headerfile name="aknviewappui.h">
    <version checksum="vuzr1EEB195UG">
      <status>OK</status>
      <comment>1) BaseConstructL()'s default param has been changed keeping binary compatibility in mind; depending on the value used by an application, S60 can determine if the application is aware of the middle softkey or not. 2) The virtual table has changed in CCoeAppUi, and is shown here as well. The change is ok, see coeaui.h for more information.</comment>
    </version>
    <version checksum="u0prJcZCJZtMT">
      <status>OK</status>
      <comment>The virtual table has changed in CCoeAppUi, and is shown here as well. The change is ok, see coeaui.h for more information.</comment>
    </version>
  </headerfile>

  <headerfile name="animationframe.h">
    <version checksum="IBqLQzqCbMtJX">
      <status>OK</status>
      <comment>The inline function still works, as iFrameInfo is still available and in the same place. There is another inline function using iFrameInfo as well, so if iFrameInfo is removed in the future it will show up in the reports.</comment>
    </version>
  </headerfile>

  <headerfile name="apaccesspointitem.h">
    <version checksum="brx+gVEA2c321">
      <status>OK</status>
      <comment>Headers compatible. Compilation fails with SDK header because some private data members are of an undefined type.</comment>
    </version>
    <version checksum="aV4Gx2NA2c321">
      <status>OK</status>
      <comment>Headers compatible. Compilation fails with SDK header because some private data members are of an undefined type.</comment>
    </version>
  </headerfile>

  <headerfile name="apaflrec.h">
    <version checksum="+QCr-dZDPCa3P">
      <status>OK</status>
      <comment>Default params removed. No impact on third party apps as long as default params are still supported (they are).</comment>
    </version>
  </headerfile>

  <headerfile name="apaserverapp.h">
    <version checksum="KiHBDyyDFayDH">
      <status>OK</status>
      <comment>Functions made const, which is ok.</comment>
    </version>
  </headerfile>

  <headerfile name="apdatahandler.h">
    <version checksum="iRmRZ+bBWYuzM">
      <status>NOK</status>
      <comment>This change is currently under investigation in S60 platform. The THandlerExtra struct is not used as a parameter to any functions, nor is it used as an accessible datamember in any class. This means that the change should not have any impact on third parties.</comment>
    </version>
  </headerfile>

  <headerfile name="apgcli.h">
    <version checksum="-hFrxyHDJJr40">
      <status>OK</status>
      <comment>1) Parameters in "removed" functions have been const'd, which is ok. 2) Return value for RollbackNonNativeApplicationsUpdates() changed from void to TInt, which is ok.</comment>
    </version>
    <version checksum="CLVjTo4DJJr40">
      <status>OK</status>
      <comment>1) Parameters in "removed" functions have been const'd, which is ok. 2) Return value for RollbackNonNativeApplicationsUpdates() changed from void to TInt, which is ok.</comment>
    </version>
    <version checksum="zBtXn7xDJJr40">
      <status>OK</status>
      <comment>1) Parameters in "removed" functions have been const'd, which is ok. 2) Return value for RollbackNonNativeApplicationsUpdates() changed from void to TInt, which is ok.</comment>
    </version>
    <version checksum="2xhOWMJDJJr40">
      <status>OK</status>
      <comment>1) Parameters in "removed" functions have been const'd, which is ok. 2) Return value for RollbackNonNativeApplicationsUpdates() changed from void to TInt, which is ok.</comment>
    </version>
    <version checksum="5YzpL5pDJJr40">
      <status>OK</status>
      <comment>1) Parameters in "removed" functions have been const'd, which is ok. 2) Return value for RollbackNonNativeApplicationsUpdates() changed from void to TInt, which is ok.</comment>
    </version>
    <version checksum="1vRtglXDJJr40">
      <status>OK</status>
      <comment>1) Parameters in "removed" functions have been const'd, which is ok. 2) Return value for RollbackNonNativeApplicationsUpdates() changed from void to TInt, which is ok.</comment>
    </version>
    <version checksum="1vRtglXAT3F23">
      <status>OK</status>
      <comment>Return value for RollbackNonNativeApplicationsUpdates() changed from void to TInt, which is ok.</comment>
    </version>
    <version checksum="CLVjTo4AT3F23">
      <status>OK</status>
      <comment>Return value for RollbackNonNativeApplicationsUpdates() changed from void to TInt, which is ok.</comment>
    </version>
  </headerfile>

  <headerfile name="apgicnfl.h">
    <version checksum="dxOGNblCQwf19">
      <status>OK</status>
      <comment>Parameters in "removed" function have been const'd, which is ok.</comment>
    </version>
  </headerfile>

  <headerfile name="apgwgnam.h">
    <version checksum="xIpxrrCApfbjw">
      <status>OK</status>
      <comment>Parameters in "removed" function have been const'd, which is ok.</comment>
    </version>
  </headerfile>

  <headerfile name="apmfndr.h">
    <version checksum="Eq0qBNGCvO98H">
      <status>OK</status>
      <comment>Size of class has not actually changed, it's a bug in the tool.</comment>
    </version>
    <version checksum="Eq0qBNGCXm9x+">
      <status>OK</status>
      <comment>Size of class has not actually changed, it's a bug in the tool.</comment>
    </version>
  </headerfile>

  <headerfile name="apmrec.h">
    <version checksum="tAQQ+doDl07WY">
      <status>OK</status>
      <comment>Offset for private data members have changed. Some of these are used in public inline functions. However, class marked @internalTechnology, so ok.</comment>
    </version>
    <version checksum="tOJx+uUAWFzSu">
      <status>OK</status>
      <comment>1) Offset for private data members have changed. Some of these are used in public inline functions. However, class marked @internalTechnology, so ok. 2) Typedef has not changed.</comment>
    </version>
    <version checksum="tOJx+uUAUOQaR">
      <status>OK</status>
      <comment>1) Offset for private data members have changed. Some of these are used in public inline functions. However, class marked @internalTechnology, so ok. 2) Typedef has not changed.</comment>
    </version>
    <version checksum="tOJx+uUBUvRSm">
      <status>OK</status>
      <comment>1) Offset for private data members have changed. Some of these are used in public inline functions. However, class marked @internalTechnology, so ok. 2) Typedef has not changed.</comment>
    </version>
  </headerfile>

  <headerfile name="asaltdefs.h">
    <version checksum="*******DG7j-J">
      <status>OK</status>
      <comment>Server version information.</comment>
    </version>
  </headerfile>

 <headerfile name="asn1dec.h">
    <version checksum="8yCphGBDsSLID">