<!DOCTYPE issuelist [
<!ELEMENT issuelist (listversion,os*,headerfile*,library*)>

<!ELEMENT listversion (#PCDATA)>

<!ELEMENT os (osversion,buildweek)>
<!ELEMENT osversion (#PCDATA)>
<!ELEMENT buildweek (#PCDATA)>

<!ELEMENT headerfile (version+)>
<!ATTLIST headerfile
			name CDATA #REQUIRED>
<!ELEMENT version (status,comment)>
<!ATTLIST version
			checksum CDATA #REQUIRED>

<!ELEMENT library (issue+)>
<!ATTLIST library
			name CDATA #REQUIRED>
<!ELEMENT issue (typeid,typeinfo?,funcname?,newfuncname?,funcpos?,newfuncpos?,bc_severity?,sc_severity?,status,comment)>
<!ELEMENT typeid (#PCDATA)>
<!ELEMENT typeinfo (#PCDATA)>
<!ELEMENT funcname (#PCDATA)>
<!ELEMENT newfuncname (#PCDATA)>
<!ELEMENT funcpos (#PCDATA)>
<!ELEMENT newfuncpos (#PCDATA)>
<!ELEMENT bc_severity (#PCDATA)>
<!ELEMENT sc_severity (#PCDATA)>

<!ELEMENT status (#PCDATA)>
<!ELEMENT comment (#PCDATA)>
]>
<issuelist>
  <listversion>2009-11-27</listversion>
	<os><osversion>3.0</osversion><buildweek>2007wk07</buildweek></os>
	<os><osversion>3.1</osversion><buildweek>2008wk07</buildweek></os>
	<os><osversion>3.2</osversion><buildweek>2009wk46</buildweek></os>
	<os><osversion>5.0</osversion><buildweek>2009wk46</buildweek></os>
  <os><osversion>5.1</osversion><buildweek>2009wk24</buildweek></os>
  <os><osversion>5.2</osversion><buildweek>2009wk46</buildweek></os>
  
    <headerfile name="stdapis\stlport\stl_user_config.h">
       <version checksum="AAAAAAAAxetVp">
      	<status>OK</status>
      	<comment>File contains nothing to be analysed.</comment>
      </version>
   </headerfile>
   <headerfile name="obex\internal\obextransportconstants.h">
       <version checksum="ci-sIZjDmQPUA">
      	<status>OK</status>
      	<comment>file is marked as internal tech.</comment>
      </version>
   </headerfile>
   <headerfile name="imcvcodc.h">
       <version checksum="LpF5YfqBjVq+a">
      	<status>OK</status>
      	<comment>Class CImConvertHeader and TImCodecB64WithLineBreaks marked as internal component.</comment>
      </version>
   </headerfile>
   
    <headerfile name="stdapis\stlport\stl\msl_string.h">
       <version checksum="qYQw59PAxetVp">
      	<status>OK</status>
      	<comment>File contains nothing to be analysed.</comment>
      </version>
   </headerfile>
   <headerfile name="caf\data.h">
       <version checksum="hAqmyPRCjBLCv">
      	<status>OK</status>
      	<comment>32bit Read is  replaced by its 64bit counterpart, it is ok</comment>
      </version>
      <version checksum="cnK4HS9CjBLCv">
      	<status>OK</status>
      	<comment>32bit Read is  replaced by its 64bit counterpart, it is ok</comment>
      </version>
   </headerfile>
   
   <headerfile name="btsecmanclient.h">
       <version checksum="tnc3gagCip1om">
      	<status>OK</status>
      	<comment>All the members marked as internal. It's not a BC break</comment>
      </version>
   </headerfile>
   
   <headerfile name="stdapis\float.h">
       <version checksum="BUEiVoyBDbca3">
      	<status>OK</status>
      	<comment>Macro has been changed. Studied and approved.</comment>
      </version>
   </headerfile>
   
    <headerfile name="stdapis\stlport\stl\debug\_relops_hash_cont.h">
       <version checksum="oewWAjJAxetVp">
      	<status>OK</status>
      	<comment>File contains nothing to be analysed.</comment>
      </version>
   </headerfile>
   
    <headerfile name="stdapis\stlport\stl\debug\_relops_cont.h">
       <version checksum="3BpCg8mAxetVp">
      	<status>OK</status>
      	<comment>File contains nothing to be analysed.</comment>
      </version>
   </headerfile>
   
    <headerfile name="stdapis\stlport\stl\_relops_template.h">
       <version checksum="AAAAAAAAxetVp">
      	<status>OK</status>
      	<comment>File contains nothing to be analysed.</comment>
      </version>
   </headerfile>
   
    <headerfile name="stdapis\stlport\stl\_relops.h">
       <version checksum="AAAAAAAAxetVp">
      	<status>OK</status>
      	<comment>File contains nothing to be analysed.</comment>
      </version>
   </headerfile>
   <headerfile name="xmlenguserdata.h">
<version checksum="CTnDet2ALeg6A">
      <status>OK</status>
      <comment>Header moved to xml/dom/xmlenguserdata.h.  Not a bc break.</comment>
    </version>
</headerfile>

<headerfile name="xmlengoutputstream.h">
<version checksum="CjkGCN0B-pGjn">
      <status>OK</status>
      <comment>Header moved to xml/dom/xmlengoutputstream.h.  Not a bc break.</comment>
    </version>
</headerfile>

<headerfile name="xmlengnodefilter.h">
<version checksum="CYqWrv5AXoCsC">
      <status>OK</status>
      <comment>Header moved to xml/dom/xmlengnodefilter.h.  Not a bc break.</comment>
    </version>
</headerfile>

<headerfile name="xmlengdomimplementation.h">
<version checksum="C3fnhbXD2Sqn0">
      <status>OK</status>
      <comment>Header moved to xml/dom/xmlengdomimplementation.h. and function close ( with default argument ) is split into parameter type and function 	without arguments. Not a BC break</comment>
    </version>
</headerfile>

<headerfile name="xmlengdocument.h">
<version checksum="CRcbgdQDjSC0A">
      <status>OK</status>
      <comment>Header moved to xml/dom/xmlengdocument.h and return value of GetDataContainerList changed from void to int. Not a BC break.</comment>
    </version>
</headerfile>

<headerfile name="xmlengdataserializer.h">
<version checksum="CqpPLPNATytCi">
      <status>OK</status>
      <comment>Header moved to xml/dom/xmlengdataserializer.h. Not a BC break</comment>
    </version>
</headerfile>

<headerfile name="xml\xmlframeworkerrors.h">
<version checksum="DG3ZQOYBJjfq6">
      <status>OK</status>
      <comment>Enumeration TXmlFrameworkPanic marked as internal technology</comment>
    </version>
</headerfile>

<headerfile name="xmlengtext.h">
<version checksum="CC4A1hFBRN5sE">
      <status>OK</status>
      <comment>Guard macro removed. Not a BC break</comment>
    </version>
</headerfile>

<headerfile name="xmlengserializationoptions.h">
<version checksum="DCb6-YoCjk2iM">
      <status>OK</status>
      <comment>Guard macro removed. Not a BC break</comment>
    </version>
</headerfile>

<headerfile name="xmlengprocessinginstruction.h">
<version checksum="DF8JAHYBhcw5i">
      <status>OK</status>
      <comment>Guard macro removed. Not a BC break</comment>
    </version>
</headerfile>

<headerfile name="xmlengnodelist_impl.h">
<version checksum="ClQQcpDC3eGWV">
      <status>OK</status>
      <comment>Guard macro removed. Not a BC break</comment>
    </version>
</headerfile>

<headerfile name="xmlengnodelist.h">
<version checksum="CRMB82WDQcTXr">
      <status>OK</status>
      <comment>Guard macro removed. Not a BC break</comment>
    </version>
</headerfile>

<headerfile name="xmlengnode.h">
<version checksum="CDYnFY6Dn4yDW">
      <status>OK</status>
      <comment>Guard macro removed. Not a BC break</comment>
    </version>
</headerfile>

<headerfile name="xmlengnamespace.h">
<version checksum="CWxAwhiA-+C8o">
      <status>OK</status>
      <comment>Guard macro removed. Not a BC break</comment>
    </version>
</headerfile>

<headerfile name="xmlengfilecontainer.h">
<version checksum="CnctmKxAwp5-Q">
      <status>OK</status>
      <comment>Guard macro removed. Not a BC break</comment>
    </version>
</headerfile>

<headerfile name="xmlengerrors.h">
<version checksum="CJl9AelAyJRqp">
      <status>OK</status>
      <comment>Guard macro removed. Not a BC break</comment>
    </version>
</headerfile>

<headerfile name="xmlengentityreference.h">
<version checksum="Cs1U16cCfsZ6T">
      <status>OK</status>
      <comment>Guard macro removed. Not a BC break</comment>
    </version>
</headerfile>

<headerfile name="xmlengelement.h">
<version checksum="CORy-voDsPfu0">
      <status>OK</status>
      <comment>Guard macro removed. Not a BC break</comment>
    </version>
</headerfile>

<headerfile name="xmlengdomparser.h">
<version checksum="CWXIb8UDWW+Ys">
      <status>OK</status>
      <comment>Guard macro removed. Not a BC break</comment>
    </version>
</headerfile>


<headerfile name="xmlengdom.h">
<version checksum="B8Zm0RuBaRDsx">
      <status>OK</status>
      <comment>Guard macro removed. Not a BC break</comment>
    </version>
</headerfile>


<headerfile name="xmlengdocumentfragment.h">
<version checksum="CxiKjemAJHPlF">
      <status>OK</status>
      <comment>Guard macro removed. Not a BC break</comment>
    </version>
</headerfile>


<headerfile name="xmlengdatacontainer.h">
<version checksum="Cnp3rHqD1iI9f">
      <status>OK</status>
      <comment>Guard macro removed. Not a BC break</comment>
    </version>
</headerfile>


<headerfile name="xmlengcomment.h">
<version checksum="CMpkSiwB4CfVl">
      <status>OK</status>
      <comment>Guard macro removed. Not a BC break</comment>
    </version>
</headerfile>


<headerfile name="xmlengchunkcontainer.h">
<version checksum="Co+n35IASQMq2">
      <status>OK</status>
      <comment>Guard macro removed. Not a BC break</comment>
    </version>
</headerfile>


<headerfile name="xmlengcharacterdata.h">
<version checksum="CmPqFK-C1iVso">
      <status>OK</status>
      <comment>Guard macro removed. Not a BC break</comment>
    </version>
</headerfile>


<headerfile name="xmlengcdatasection.h">
<version checksum="CgkWunIBqSXuT">
      <status>OK</status>
      <comment>Guard macro removed. Not a BC break</comment>
    </version>
</headerfile>

<headerfile name="xmlengbinarycontainer.h">
<version checksum="CvdpY3zBdYkzj">
      <status>OK</status>
      <comment>Guard macro removed. Not a BC break</comment>
    </version>
</headerfile>

<headerfile name="xmlengattr.h">
<version checksum="CC1c8WrB7h8b4">
      <status>OK</status>
      <comment>Guard macro removed. Not a BC break</comment>
    </version>
</headerfile>

   
   <headerfile name="apaid.h">
       <version checksum="m53Qn2rDV2jn2">
      	<status>OK</status>
      	<comment> CApaAppFinder and TApaAppCapability::Internalize7_0L( ::RReadStream) marked as deprecated. The published All TApaAppEntry class is reclassified as internalComponent. It's not a BC break.</comment>
      </version>
   </headerfile>
   
      <headerfile name="apasvst.h">
       <version checksum="Ww303n5B+I26w">
      	<status>OK</status>
      	<comment>Removal of unused exported StartupApaServer(MApaAppStarter ) function is approved and changing the parameter of IMPORT_C TInt ApaServThreadStart(TAny* )is approved. It's not a BC break.</comment>
      </version>
   </headerfile>
   
    <headerfile name="stdapis\stlport\stl\_exception.h">
       <version checksum="AAAAAAAAxetVp">
      	<status>OK</status>
      	<comment>File contains nothing to be analysed.</comment>
      </version>
   </headerfile>
   
    <headerfile name="stdapis\stlport\stl\_config_compat.h">
       <version checksum="FAZh1S9AxetVp">
      	<status>OK</status>
      	<comment>File contains nothing to be analysed.</comment>
      </version>
   </headerfile>
   
    <headerfile name="stdapis\stlport\stl\_check_config.h">
       <version checksum="YV+e7JCAxetVp">
      	<status>OK</status>
      	<comment>File contains nothing to be analysed.</comment>
      </version>
   </headerfile>
   
    <headerfile name="stdapis\stlport\config\_prolog.h">
       <version checksum="6l8t-o+AxetVp">
      	<status>OK</status>
      	<comment>File contains nothing to be analysed.</comment>
      </version>
   </headerfile>
   
    <headerfile name="stdapis\stlport\config\_msvc_warnings_off.h">
       <version checksum="Qvw86pYAxetVp">
      	<status>OK</status>
      	<comment>File contains nothing to be analysed.</comment>
      </version>
   </headerfile>
   
   <headerfile name="stdapis\stlport\config\_epilog.h">
       <version checksum="jPYNvoiAxetVp">
      	<status>OK</status>
      	<comment>File contains nothing to be analysed.</comment>
      </version>
   </headerfile>
   
    <headerfile name="osextensions\stdapis\stlport\stl_user_config.h">
       <version checksum="AAAAAAAAxetVp">
      	<status>OK</status>
      	<comment>File contains nothing to be analysed.</comment>
      </version>
   </headerfile>
   
    <headerfile name="osextensions\stdapis\stlport\stl\msl_string.h">
       <version checksum="qYQw59PAxetVp">
      	<status>OK</status>
      	<comment>File contains nothing to be analysed.</comment>
      </version>
   </headerfile>
   
    <headerfile name="osextensions\stdapis\stlport\stl\debug\_relops_hash_cont.h">
       <version checksum="oewWAjJAxetVp">
      	<status>OK</status>
      	<comment>File contains nothing to be analysed.</comment>
      </version>
   </headerfile>
   
    <headerfile name="osextensions\stdapis\stlport\stl\debug\_relops_cont.h">
       <version checksum="3BpCg8mAxetVp">
      	<status>OK</status>
      	<comment>File contains nothing to be analysed.</comment>
      </version>
   </headerfile>
   
    <headerfile name="osextensions\stdapis\stlport\stl\_relops_template.h">
       <version checksum="AAAAAAAAxetVp">
      	<status>OK</status>
      	<comment>File contains nothing to be analysed.</comment>
      </version>
   </headerfile>
   
    <headerfile name="osextensions\stdapis\stlport\stl\_relops.h">
       <version checksum="AAAAAAAAxetVp">
      	<status>OK</status>
      	<comment>File contains nothing to be analysed.</comment>
      </version>
   </headerfile>
   
    <headerfile name="osextensions\stdapis\stlport\stl\_exception.h">
       <version checksum="AAAAAAAAxetVp">
      	<status>OK</status>
      	<comment>File contains nothing to be analysed.</comment>
      </version>
   </headerfile>
   
    <headerfile name="osextensions\stdapis\stlport\stl\_config_compat.h">
       <version checksum="FAZh1S9AxetVp">
      	<status>OK</status>
      	<comment>File contains nothing to be analysed.</comment>
      </version>
   </headerfile>
   
    <headerfile name="osextensions\stdapis\stlport\stl\_check_config.h">
       <version checksum="YV+e7JCAxetVp">
      	<status>OK</status>
      	<comment>File contains nothing to be analysed.</comment>
      </version>
   </headerfile>
   
    <headerfile name="osextensions\stdapis\stlport\config\_prolog.h">
       <version checksum="6l8t-o+AxetVp">
      	<status>OK</status>
      	<comment>File contains nothing to be analysed.</comment>
      </version>
   </headerfile>
   
    <headerfile name="osextensions\stdapis\stlport\config\_msvc_warnings_off.h">
       <version checksum="Qvw86pYAxetVp">
      	<status>OK</status>
      	<comment>File contains nothing to be analysed.</comment>
      </version>
   </headerfile>
   <headerfile name="_sdpdefs.h">
    <version checksum="KU1qkzbAxetVp">
      <status>OK</status>
      <comment>File contains only #defines.</comment>
    </version>
   </headerfile>

   <headerfile name="app\mmsconst.h">
       <version checksum="+rxMH4DD28R5R">
      	<status>OK</status>
      	<comment>Intialization value of KMmsResourceDriveAndFile is changed from "z:mmsserver.rsc" to "mmsserver.rsc" .</comment>
      </version>
   </headerfile>
     
  <headerfile name="mw\eikseced.h">
    <version checksum="uMQoI+aBhyNRy">
      <status>OK</status>
      <comment>Class has default public constructor, so overriding a virtual funtion is not allowed.But this change has been done to fix a bug. Studied and approved.</comment>
    </version>
    <version checksum="wWHDCdEBhyNRy">
      <status>OK</status>
      <comment>Class has default public constructor, so overriding a virtual funtion is not allowed.But this change has been done to fix a bug. Studied and approved.</comment>
    </version>
  </headerfile>
   <headerfile name="_sipcodecdefs.h">
    <version checksum="KhNActGAxetVp">
      <status>OK</status>
      <comment>File contains only #defines.</comment>
    </version>
  </headerfile>
  <headerfile name="eikseced.h">
   <version checksum="h1ch7z2BhyNRy">
      <status>OK</status>
      <comment>Class has default public constructor, so overriding a virtual funtion is not allowed.But this change has been done to fix a bug. Studied and approved.</comment>
    </version>
  </headerfile>
  <headerfile name="middleware\eikseced.h">
   <version checksum="wWHDCdEBhyNRy">
      <status>OK</status>
      <comment>Class has default public constructor, so overriding a virtual funtion is not allowed.But this change has been done to fix a bug. Studied and approved.</comment>
    </version>
  </headerfile>
  
  <headerfile name="mproengprofile.h">
   <version checksum="vMnWRNXCdEV2C">
      <status>NOK</status>
      <comment>Virtual function added to the derivable class.It is a bc break.</comment>
    </version>
  </headerfile>
  
  <headerfile name="nifvar.h">
    <version checksum="YzF7ILnAWEwi1">
      <status>OK</status>
      <comment>Various enum members removed.Studied and approved</comment>
    </version>
    <version checksum="3fIAnGJAWEwi1">
      <status>OK</status>
      <comment>Various enum members removed.Studied and approved</comment>
    </version>
    <version checksum="OxqYJSJAWEwi1">
      <status>OK</status>
      <comment>Various enum members removed.Studied and approved</comment>
    </version>
  </headerfile>

  <headerfile name="agentdialog.h">
    <version checksum="*******AaopJx">
      <status>OK</status>
      <comment>This breaks compatibility, but both class and file are marked @internalTechnology and should not be used by third parties.</comment>
    </version>
  </headerfile>
  
  <headerfile name="aknappui.h">
    <version checksum="beh07ATCbPbTg">
      <status>OK</status>
      <comment>1) Enumerations and BaseConstructL()'s default param have been changed keeping binary compatibility in mind; depending on the input values (enum or param) used by an application, S60 can determine if the application is aware of the middle softkey or not. 2) The name of SetLocalUiZoomL() has been changed to SetLocalUiZoom(). This is ok from BC point of view. 3) The virtual table has changed in CCoeAppUi, and is shown here as well. The change is ok, see coeaui.h for more information.</comment>
    </version>
    <version checksum="P8rAG-hDAflx7">
      <status>OK</status>
      <comment>1) The name of SetLocalUiZoomL() has been changed to SetLocalUiZoom(). This is ok from BC point of view. 2) The virtual table has changed in CCoeAppUi, and is shown here as well. The change is ok, see coeaui.h for more information.</comment>
    </version>
    <version checksum="Y1xBFapDAflx7">
      <status>OK</status>
      <comment>1) The name of SetLocalUiZoomL() has been changed to SetLocalUiZoom(). This is ok from BC point of view. 2) The virtual table has changed in CCoeAppUi, and is shown here as well. The change is ok, see coeaui.h for more information.</comment>
    </version>
    <version checksum="cgrMqv4DAflx7">
      <status>OK</status>
      <comment>1) The name of SetLocalUiZoomL() has been changed to SetLocalUiZoom(). This is ok from BC point of view. 2) The virtual table has changed in CCoeAppUi, and is shown here as well. The change is ok, see coeaui.h for more information.</comment>
    </version>
  </headerfile>
  
  <headerfile name="akncheckboxsettingpage.h">
    <version checksum="OWci+NoDEnmh8">
      <status>OK</status>
      <comment>This overridden function will not be called in applications, which derive from this class and are built with the SDK. Generally, this may cause unexpected behaviour. However, the effects of this particular change have been studied and approved.</comment>
    </version>
  </headerfile>
  
  <headerfile name="aknclearer.h">
    <version checksum="-bqb7sODGTJll">
      <status>OK</status>
      <comment>This overridden function will not be called in applications, which derive from this class and are built with the SDK. Generally, this may cause unexpected behaviour. However, the effects of this particular change have been studied and approved.</comment>
    </version>
  </headerfile>  
  
<headerfile name="mw\downloadmgrclient.h">
    <version checksum="w5+w-cfA8hYTQ">
      <status>NOK</status>
      <comment>Class size changed. Since class has public destructor, memory required for an object of this class would be determined during build time only.It is a break.</comment>
    </version>
    <version checksum="PJE3SBtAR8hV8">
      <status>OK</status>
      <comment>Part of internal tech.</comment>
    </version>
    <version checksum="RV1dRnEAR8hV8">
      <status>OK</status>
      <comment>Part of internal tech.</comment>
    </version>
  </headerfile>
  
  <headerfile name="hwrmlight.h">
    <version checksum="EHbF2jRAfT4pi">
      <status>OK</status>
      <comment>Class size changed, but it is not derivable and NewL is used for creation of object.</comment>
    </version>
    <version checksum="rTi1pv1Abvrqq">
      <status>OK</status>
      <comment>Class(CHWRMLight) size changed, but it is not derivable and NewL is used for creation of object.</comment>
    </version>
</headerfile>  
  <headerfile name="apadef.h">
    <version checksum="HoHnUnMDtBH5y">
      <status>OK</status>
      <comment>All removed constants are internal or deprecated..</comment>
    </version>
  </headerfile>
  <headerfile name="apgdoor.h">
    <version checksum="Gn4jJ9FAQuYDB">
      <status>OK</status>
      <comment>All removed constants are marked as internal tech.</comment>
    </version>
  </headerfile>
  <headerfile name="mw\eiklbv.h">
    <version checksum="PGCWS6pBtCXSS">
      <status>OK</status>
      <comment>Spare data member is replaced with original data member.</comment>
    </version>
    <version checksum="QuQ+FBfBtCXSS">
      <status>OK</status>
      <comment>Spare data member is replaced with original data member.</comment>
    </version>
    <version checksum="o1wC0U5BtCXSS">
      <status>OK</status>
      <comment>Spare data member is replaced with original data member.</comment>
    </version>
    <version checksum="UtWyArIBtCXSS">
      <status>OK</status>
      <comment>Spare data member is replaced with original data member.</comment>
    </version>
  </headerfile>
  <headerfile name="middleware\msenproviderpolicy.h">
    <version checksum="uaJHt4oCyqeoq">
      <status>NOK</status>
      <comment>class MSenProviderPolicy has default constructor(compiler injected), thus adding virtual functions would change the v-table layout of derived class..</comment>
    </version>
  </headerfile>
  <headerfile name="nifman.h">
    <version checksum="9-L6g7EAR8hV8">
      <status>OK</status>
      <comment>Part of internal tech.</comment>
    </version>
    <version checksum="PJE3SBtAR8hV8">
      <status>OK</status>
      <comment>Part of internal tech.</comment>
    </version>
    <version checksum="RV1dRnEAR8hV8">
      <status>OK</status>
      <comment>Part of internal tech.</comment>
    </version>
    <version checksum="ecfSwmeAR8hV8">
      <status>OK</status>
      <comment>Part of internal tech.</comment>
    </version>
    <version checksum="YJAHCSGAR8hV8">
      <status>OK</status>
      <comment>Part of internal tech.</comment>
    </version>
  </headerfile>  
  <headerfile name="apadbase.h">
    <version checksum="fonxBFDDvghWj">
      <status>OK</status>
      <comment>Reserved member renamed.</comment>
    </version>
  </headerfile>
  
  <headerfile name="msvipc.h">
    <version checksum="9-L6g7EAR8hV8">
      <status>OK</status>
      <comment>Part of internal tech.</comment>
    </version>
    <version checksum="z0uxWyvDv6Mua">
      <status>OK</status>
      <comment>Part of internal tech.</comment>
    </version>
    <version checksum="1nfKn9WDv6Mua">
      <status>OK</status>
      <comment>Part of internal tech.</comment>
    </version>
    <version checksum="Z2-a7LMDv6Mua">
      <status>OK</status>
      <comment>Part of internal tech.</comment>
    </version>
  </headerfile>
  
  <headerfile name="tzlocalizationdatatypes.h">
    <version checksum="0rbmNDTA7au+1">
      <status>OK</status>
      <comment>tzlocalizationdatatypes.h is part of internal tech...</comment>
    </version>
  </headerfile>
   <headerfile name="mw\msenproviderpolicy.h">
    <version checksum="uaJHt4oCyqeoq">
      <status>NOK</status>
      <comment>class MSenProviderPolicy has default constructor(compiler injected), thus adding virtual functions would change the v-table layout of derived class..</comment>
    </version>
  </headerfile>
  <headerfile name="symcpp.h">
    <version checksum="03zR6g5Cfj+v9">
      <status>OK</status>
      <comment>All removed functions are part of #else part.</comment>
    </version>
  </headerfile>
   
	<headerfile name="akngrid.h">
    <version checksum="+ckDXAkDrcxXC">
      <status>OK</status>
      <comment>The removed data member is not used in any inline functions.</comment>
    </version>
    <version checksum="DCh2DNWBOffau">
      <status>NOK</status>
      <comment>This overridden function will not be called in applications, which derive from this class and are built with the SDK. Generally, this may cause unexpected behaviour.</comment>
    </version>
    <version checksum="DA3Z-T4BOffau">
      <status>OK</status>
      <comment>ignored issue.</comment>
    </version>
  </headerfile>
  
  <headerfile name="clkmdlobserver.h">
    <version checksum="JJzr6d2Cip1om">
      <status>OK</status>
      <comment>This file gets depreciated, removal of file consequences studied and approved.</comment>
    </version>
  </headerfile>
  
  <headerfile name="babackup.h">
    <version checksum="b4wS9q-BRxrqr">
      <status>OK</status>
      <comment>It's commented that CBaBackupSessionWrapper::CloseServer( ) should not be used.</comment>
    </version>
     </headerfile>

   <headerfile name="middleware\akngrid.h">
    <version checksum="DCh2DNWBOffau">
      <status>NOK</status>
      <comment>This overridden function will not be called in applications, which derive from this class and are built with the SDK. Generally, this may cause unexpected behaviour.</comment>
    </version>
    <version checksum="CWr04KWBOffau">
      <status>OK</status>
      <comment>ignored BC-break.</comment>
    </version>
  </headerfile>
  
  <headerfile name="middleware\aknquerydialog.h">
    <version checksum="ftKNtwtBjJUuZ">
      <status>OK</status>
      <comment>1.Spare member has been changed. 2.Virtual function has been overridden, since public constructor is not allowed to use , this won't be a problem</comment>
    </version>
    <version checksum="jgpjZYlBjJUuZ">
      <status>OK</status>
      <comment>1.Spare member has been changed. 2.Virtual function has been overridden, since public constructor is not allowed to use , this won't be a problem</comment>
    </version>
  </headerfile>

  <headerfile name="middleware\ptilanguage.h">
    <version checksum="o-J6SbTDc57p9">
      <status>OK</status>
      <comment>Class size is not changed, removed data members are not used in any inline function.</comment>
    </version>
  </headerfile>
  <headerfile name="mw\ptilanguage.h">
    <version checksum="o-J6SbTDc57p9">
      <status>OK</status>
      <comment>Class size is not changed, removed data members are not used in any inline function.</comment>
    </version>
  </headerfile>

  <headerfile name="aknmessagequerycontrol.h">
    <version checksum="1NXomtIBe7mhN">
      <status>OK</status>
      <comment>Private data member iSpare is not used in any inline functions (or in any other way for that matter), so it's ok to replace it.</comment>
    </version>
    <version checksum="*******CW6Yiy">
      <status>OK</status>
      <comment>The only data member used in an inline function is iNumberOfLines. The offset of this data member has not changed, so ok.</comment>
    </version>
    <version checksum="*******A29o2i">
      <status>OK</status>
      <comment>The only data member used in an inline function is iNumberOfLines. The offset of this data member has not changed, so ok.</comment>
    </version>
    <version checksum="5ATmXWUB2a2mi">
      <status>OK</status>
      <comment>The only data member used in an inline function is iNumberOfLines. The offset of this data member has not changed, so ok.</comment>
    </version>
    <version checksum="5ATmXWUCYQkjO">
      <status>OK</status>
      <comment>The only data member used in an inline function is iNumberOfLines. The offset of this data member has not changed, so ok.</comment>
    </version>
    <version checksum="8lXP5wPCYQkjO">
      <status>OK</status>
      <comment>The only data member used in an inline function is iNumberOfLines. The offset of this data member has not changed, so ok.</comment>
    </version>
  </headerfile>
  
 	<headerfile name="middleware\aknmessagequerycontrol.h">
    <version checksum="5ATmXWUCYQkjO">
      <status>OK</status>
      <comment>The only data member used in an inline function is iNumberOfLines. The offset of this data member has not changed, so ok.</comment>
    </version>
    <version checksum="8lXP5wPCYQkjO">
      <status>OK</status>
      <comment>The only data member used in an inline function is iNumberOfLines. The offset of this data member has not changed, so ok.</comment>
    </version>
     <version checksum="D7TIJO2AsEPr5">
      <status>NOK</status>