<!DOCTYPE issuelist [
<!ELEMENT issuelist (listversion,os*,headerfile*,library*)>

<!ELEMENT listversion (#PCDATA)>

<!ELEMENT os (osversion,buildweek)>
<!ELEMENT osversion (#PCDATA)>
<!ELEMENT buildweek (#PCDATA)>

<!ELEMENT headerfile (version+)>
<!ATTLIST headerfile
			name CDATA #REQUIRED>
<!ELEMENT version (status,comment)>
<!ATTLIST version
			checksum CDATA #REQUIRED>

<!ELEMENT library (issue+)>
<!ATTLIST library
			name CDATA #REQUIRED>
<!ELEMENT issue (typeid,typeinfo?,funcname?,newfuncname?,funcpos?,newfuncpos?,bc_severity?,sc_severity?,status,comment)>
<!ELEMENT typeid (#PCDATA)>
<!ELEMENT typeinfo (#PCDATA)>
<!ELEMENT funcname (#PCDATA)>
<!ELEMENT newfuncname (#PCDATA)>
<!ELEMENT funcpos (#PCDATA)>
<!ELEMENT newfuncpos (#PCDATA)>
<!ELEMENT bc_severity (#PCDATA)>
<!ELEMENT sc_severity (#PCDATA)>

<!ELEMENT status (#PCDATA)>
<!ELEMENT comment (#PCDATA)>
]>

<!--
- Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
- All rights reserved.
- This component and the accompanying materials are made available
- under the terms of the License "Eclipse Public License v1.0"
- which accompanies this distribution, and is available
- at the URL "http://www.eclipse.org/legal/epl-v10.html".
- 
- Initial Contributors:
- Nokia Corporation - initial contribution.
- 
- Contributors:
- 
- Description:
- 
-->
<issuelist>
  <listversion>2009-06-12</listversion>
	<os><osversion>3.0</osversion><buildweek>2007wk07</buildweek></os>
	<os><osversion>3.1</osversion><buildweek>2008wk07</buildweek></os>
	<os><osversion>3.2</osversion><buildweek>2009wk17</buildweek></os>
	<os><osversion>5.0</osversion><buildweek>2009wk22</buildweek></os>
  <os><osversion>5.1</osversion><buildweek>2009wk22</buildweek></os>
  <os><osversion>5.2</osversion><buildweek>2009wk20</buildweek></os>
  
    <headerfile name="stdapis\stlport\stl_user_config.h">
       <version checksum="AAAAAAAAxetVp">
      	<status>OK</status>
      	<comment>File contains nothing to be analysed.</comment>
      </version>
   </headerfile>
   
    <headerfile name="stdapis\stlport\stl\msl_string.h">
       <version checksum="qYQw59PAxetVp">
      	<status>OK</status>
      	<comment>File contains nothing to be analysed.</comment>
      </version>
   </headerfile>
   <headerfile name="caf\data.h">
       <version checksum="hAqmyPRCjBLCv">
      	<status>OK</status>
      	<comment>32bit Read is  replaced by its 64bit counterpart, it is ok</comment>
      </version>
   </headerfile>
   
    <headerfile name="stdapis\stlport\stl\debug\_relops_hash_cont.h">
       <version checksum="oewWAjJAxetVp">
      	<status>OK</status>
      	<comment>File contains nothing to be analysed.</comment>
      </version>
   </headerfile>
   
    <headerfile name="stdapis\stlport\stl\debug\_relops_cont.h">
       <version checksum="3BpCg8mAxetVp">
      	<status>OK</status>
      	<comment>File contains nothing to be analysed.</comment>
      </version>
   </headerfile>
   
    <headerfile name="stdapis\stlport\stl\_relops_template.h">
       <version checksum="AAAAAAAAxetVp">
      	<status>OK</status>
      	<comment>File contains nothing to be analysed.</comment>
      </version>
   </headerfile>
   
    <headerfile name="stdapis\stlport\stl\_relops.h">
       <version checksum="AAAAAAAAxetVp">
      	<status>OK</status>
      	<comment>File contains nothing to be analysed.</comment>
      </version>
   </headerfile>
   
   <headerfile name="apaid.h">
       <version checksum="m53Qn2rDV2jn2">
      	<status>OK</status>
      	<comment> CApaAppFinder and TApaAppCapability::Internalize7_0L( ::RReadStream) marked as deprecated. The published All TApaAppEntry class is reclassified as internalComponent. It's not a BC break.</comment>
      </version>
   </headerfile>
   
      <headerfile name="apasvst.h">
       <version checksum="Ww303n5B+I26w">
      	<status>OK</status>
      	<comment>Removal of unused exported StartupApaServer(MApaAppStarter ) function is approved and changing the parameter of IMPORT_C TInt ApaServThreadStart(TAny* )is approved. It's not a BC break.</comment>
      </version>
   </headerfile>
   
    <headerfile name="stdapis\stlport\stl\_exception.h">
       <version checksum="AAAAAAAAxetVp">
      	<status>OK</status>
      	<comment>File contains nothing to be analysed.</comment>
      </version>
   </headerfile>
   
    <headerfile name="stdapis\stlport\stl\_config_compat.h">
       <version checksum="FAZh1S9AxetVp">
      	<status>OK</status>
      	<comment>File contains nothing to be analysed.</comment>
      </version>
   </headerfile>
   
    <headerfile name="stdapis\stlport\stl\_check_config.h">
       <version checksum="YV+e7JCAxetVp">
      	<status>OK</status>
      	<comment>File contains nothing to be analysed.</comment>
      </version>
   </headerfile>
   
    <headerfile name="stdapis\stlport\config\_prolog.h">
       <version checksum="6l8t-o+AxetVp">
      	<status>OK</status>
      	<comment>File contains nothing to be analysed.</comment>
      </version>
   </headerfile>
   
    <headerfile name="stdapis\stlport\config\_msvc_warnings_off.h">
       <version checksum="Qvw86pYAxetVp">
      	<status>OK</status>
      	<comment>File contains nothing to be analysed.</comment>
      </version>
   </headerfile>
   
   <headerfile name="stdapis\stlport\config\_epilog.h">
       <version checksum="jPYNvoiAxetVp">
      	<status>OK</status>
      	<comment>File contains nothing to be analysed.</comment>
      </version>
   </headerfile>
   
    <headerfile name="osextensions\stdapis\stlport\stl_user_config.h">
       <version checksum="AAAAAAAAxetVp">
      	<status>OK</status>
      	<comment>File contains nothing to be analysed.</comment>
      </version>
   </headerfile>
   
    <headerfile name="osextensions\stdapis\stlport\stl\msl_string.h">
       <version checksum="qYQw59PAxetVp">
      	<status>OK</status>
      	<comment>File contains nothing to be analysed.</comment>
      </version>
   </headerfile>
   
    <headerfile name="osextensions\stdapis\stlport\stl\debug\_relops_hash_cont.h">
       <version checksum="oewWAjJAxetVp">
      	<status>OK</status>
      	<comment>File contains nothing to be analysed.</comment>
      </version>
   </headerfile>
   
    <headerfile name="osextensions\stdapis\stlport\stl\debug\_relops_cont.h">
       <version checksum="3BpCg8mAxetVp">
      	<status>OK</status>
      	<comment>File contains nothing to be analysed.</comment>
      </version>
   </headerfile>
   
    <headerfile name="osextensions\stdapis\stlport\stl\_relops_template.h">
       <version checksum="AAAAAAAAxetVp">
      	<status>OK</status>
      	<comment>File contains nothing to be analysed.</comment>
      </version>
   </headerfile>
   
    <headerfile name="osextensions\stdapis\stlport\stl\_relops.h">
       <version checksum="AAAAAAAAxetVp">
      	<status>OK</status>
      	<comment>File contains nothing to be analysed.</comment>
      </version>
   </headerfile>
   
    <headerfile name="osextensions\stdapis\stlport\stl\_exception.h">
       <version checksum="AAAAAAAAxetVp">
      	<status>OK</status>
      	<comment>File contains nothing to be analysed.</comment>
      </version>
   </headerfile>
   
    <headerfile name="osextensions\stdapis\stlport\stl\_config_compat.h">
       <version checksum="FAZh1S9AxetVp">
      	<status>OK</status>
      	<comment>File contains nothing to be analysed.</comment>
      </version>
   </headerfile>
   
    <headerfile name="osextensions\stdapis\stlport\stl\_check_config.h">
       <version checksum="YV+e7JCAxetVp">
      	<status>OK</status>
      	<comment>File contains nothing to be analysed.</comment>
      </version>
   </headerfile>
   
    <headerfile name="osextensions\stdapis\stlport\config\_prolog.h">
       <version checksum="6l8t-o+AxetVp">
      	<status>OK</status>
      	<comment>File contains nothing to be analysed.</comment>
      </version>
   </headerfile>
   
    <headerfile name="osextensions\stdapis\stlport\config\_msvc_warnings_off.h">
       <version checksum="Qvw86pYAxetVp">
      	<status>OK</status>
      	<comment>File contains nothing to be analysed.</comment>
      </version>
   </headerfile>
   <headerfile name="app\mmsconst.h">
       <version checksum="+rxMH4DD28R5R">
      	<status>OK</status>
      	<comment>Intialization value of KMmsResourceDriveAndFile is changed from "z:mmsserver.rsc" to "mmsserver.rsc" .</comment>
      </version>
   </headerfile>
     
  <headerfile name="mw\eikseced.h">
    <version checksum="uMQoI+aBhyNRy">
      <status>OK</status>
      <comment>Class has default public constructor, so overriding a virtual funtion is not allowed.But this change has been done to fix a bug. Studied and approved.</comment>
    </version>
    <version checksum="wWHDCdEBhyNRy">
      <status>OK</status>
      <comment>Class has default public constructor, so overriding a virtual funtion is not allowed.But this change has been done to fix a bug. Studied and approved.</comment>
    </version>
  </headerfile>
  
  <headerfile name="hwrmlight.h">
    <version checksum="EHbF2jRAfT4pi">
      <status>OK</status>
      <comment>Class size changed, but it is not derivable and NewL is used for creation of object.</comment>
    </version>
  </headerfile>
  <headerfile name="apadef.h">
    <version checksum="HoHnUnMDtBH5y">
      <status>OK</status>
      <comment>All removed constants are internal or deprecated..</comment>
    </version>
  </headerfile>
  <headerfile name="apaserverapp.h">
    <version checksum="UAIn8MzAz54vh">
      <status>OK</status>
      <comment>Guard macro changed..</comment>
    </version>
  </headerfile>
  <headerfile name="apgcli.h">
    <version checksum="u-+VJVrAWWgc3">
      <status>OK</status>
      <comment>Enum values are not removed.A name has been given to a nameless enumeration</comment>
    </version>
  </headerfile>
  <headerfile name="apgdoor.h">
    <version checksum="Gn4jJ9FAQuYDB">
      <status>OK</status>
      <comment>All removed constants are marked as internal tech.</comment>
    </version>
  </headerfile>
    
  <headerfile name="nifman.h">
    <version checksum="9-L6g7EAR8hV8">
      <status>OK</status>
      <comment>Part of internal tech.</comment>
    </version>
    <version checksum="PJE3SBtAR8hV8">
      <status>OK</status>
      <comment>Part of internal tech.</comment>
    </version>
  </headerfile>
  <headerfile name="apadbase.h">
    <version checksum="fonxBFDDvghWj">
      <status>OK</status>
      <comment>Reserved member renamed.</comment>
    </version>
  </headerfile>
  
  <headerfile name="msvipc.h">
    <version checksum="9-L6g7EAR8hV8">
      <status>OK</status>
      <comment>Part of internal tech.</comment>
    </version>
    <version checksum="z0uxWyvDv6Mua">
      <status>OK</status>
      <comment>Part of internal tech.</comment>
    </version>
  </headerfile>
  
  <headerfile name="tzlocalizationdatatypes.h">
    <version checksum="0rbmNDTA7au+1">
      <status>OK</status>
      <comment>tzlocalizationdatatypes.h is part of internal tech...</comment>
    </version>
  </headerfile>
   <headerfile name="mw\msenproviderpolicy.h">
    <version checksum="uaJHt4oCyqeoq">
      <status>NOK</status>
      <comment>class MSenProviderPolicy has default constructor(compiler injected), thus adding virtual functions would change the v-table layout of derived class..</comment>
    </version>
  </headerfile>
  <headerfile name="symcpp.h">
    <version checksum="03zR6g5Cfj+v9">
      <status>OK</status>
      <comment>All removed functions are part of #else part.</comment>
    </version>
  </headerfile>
   
	<headerfile name="akngrid.h">
    <version checksum="+ckDXAkDrcxXC">
      <status>OK</status>
      <comment>The removed data member is not used in any inline functions.</comment>
    </version>
    <version checksum="DCh2DNWBOffau">
      <status>NOK</status>
      <comment>This overridden function will not be called in applications, which derive from this class and are built with the SDK. Generally, this may cause unexpected behaviour.</comment>
    </version>
    <version checksum="DA3Z-T4BOffau">
      <status>OK</status>
      <comment>ignored issue.</comment>
    </version>
  </headerfile>
  
  <headerfile name="clkmdlobserver.h">
    <version checksum="JJzr6d2Cip1om">
      <status>OK</status>
      <comment>This file gets depreciated, removal of file consequences studied and approved.</comment>
    </version>
  </headerfile>
  
  <headerfile name="babackup.h">
    <version checksum="b4wS9q-BRxrqr">
      <status>OK</status>
      <comment>It's commented that CBaBackupSessionWrapper::CloseServer( ) should not be used.</comment>
    </version>
     </headerfile>

   <headerfile name="middleware\akngrid.h">
    <version checksum="DCh2DNWBOffau">
      <status>NOK</status>
      <comment>This overridden function will not be called in applications, which derive from this class and are built with the SDK. Generally, this may cause unexpected behaviour.</comment>
    </version>
    <version checksum="CWr04KWBOffau">
      <status>OK</status>
      <comment>ignored BC-break.</comment>
    </version>
  </headerfile>
  
  <headerfile name="middleware\aknquerydialog.h">
    <version checksum="ftKNtwtBjJUuZ">
      <status>OK</status>
      <comment>1.Spare member has been changed. 2.Virtual function has been overridden, since public constructor is not allowed to use , this won't be a problem</comment>
    </version>
    <version checksum="jgpjZYlBjJUuZ">
      <status>OK</status>
      <comment>1.Spare member has been changed. 2.Virtual function has been overridden, since public constructor is not allowed to use , this won't be a problem</comment>
    </version>
  </headerfile>

  <headerfile name="middleware\ptilanguage.h">
    <version checksum="o-J6SbTDc57p9">
      <status>OK</status>
      <comment>Class size is not changed, removed data members are not used in any inline function.</comment>
    </version>
  </headerfile>
  <headerfile name="mw\ptilanguage.h">
    <version checksum="o-J6SbTDc57p9">
      <status>OK</status>
      <comment>Class size is not changed, removed data members are not used in any inline function.</comment>
    </version>
  </headerfile>

  <headerfile name="aknmessagequerycontrol.h">
    <version checksum="1NXomtIBe7mhN">
      <status>OK</status>
      <comment>Private data member iSpare is not used in any inline functions (or in any other way for that matter), so it's ok to replace it.</comment>
    </version>
    <version checksum="*******CW6Yiy">
      <status>OK</status>
      <comment>The only data member used in an inline function is iNumberOfLines. The offset of this data member has not changed, so ok.</comment>
    </version>
    <version checksum="*******A29o2i">
      <status>OK</status>
      <comment>The only data member used in an inline function is iNumberOfLines. The offset of this data member has not changed, so ok.</comment>
    </version>
    <version checksum="5ATmXWUB2a2mi">
      <status>OK</status>
      <comment>The only data member used in an inline function is iNumberOfLines. The offset of this data member has not changed, so ok.</comment>
    </version>
    <version checksum="5ATmXWUCYQkjO">
      <status>OK</status>
      <comment>The only data member used in an inline function is iNumberOfLines. The offset of this data member has not changed, so ok.</comment>
    </version>
    <version checksum="8lXP5wPCYQkjO">
      <status>OK</status>
      <comment>The only data member used in an inline function is iNumberOfLines. The offset of this data member has not changed, so ok.</comment>
    </version>
  </headerfile>
  
 	<headerfile name="middleware\aknmessagequerycontrol.h">
    <version checksum="5ATmXWUCYQkjO">
      <status>OK</status>
      <comment>The only data member used in an inline function is iNumberOfLines. The offset of this data member has not changed, so ok.</comment>
    </version>
    <version checksum="8lXP5wPCYQkjO">
      <status>OK</status>
      <comment>The only data member used in an inline function is iNumberOfLines. The offset of this data member has not changed, so ok.</comment>
    </version>
     <version checksum="D7TIJO2AsEPr5">
      <status>NOK</status>
      <comment>1.Class is NONSHARABLE, so adding a virtual function won't break BC. 2.iNumberOfLines changed its offset although used in inline function, it constitutes a break.</comment>
    </version>
     <version checksum="GcUpzDeCFnzlJ">
      <status>OK</status>
      <comment>The only data member used in an inline function is iNumberOfLines. The offset of this data member has not changed, so ok.</comment>
    </version>
  </headerfile>

  <headerfile name="lafmain.h">
    <version checksum="KRUicopBZyyu4">
      <status>OK</status>
      <comment>v-table layout of CLafEdwinCustomDrawBase changed due to change in base class layout. But it is ok, since reserved virtual function has been replaced..</comment>
    </version>
  </headerfile>
  
  <headerfile name="aknnotifystd.h">
    <version checksum="D-1xugsBA7hej">
      <status>OK</status>
      <comment>Struct SAknBatteryNotifyParams is marked @internal</comment>
    </version>
  </headerfile>
  
  <headerfile name="middleware\aknnotifystd.h">
    <version checksum="D-1xugsBA7hej">
      <status>OK</status>
      <comment>Struct SAknBatteryNotifyParams is marked @internal</comment>
    </version>
  </headerfile>
  
  <headerfile name="middleware\aknquerydialog.h">
    <version checksum="ftKNtwtBjJUuZ">
      <status>NOK</status>
      <comment>Virtual functions overrideen in deliverable class. Will not be called in clients deriving from this class</comment>
    </version>
  </headerfile>
  
  <headerfile name="aknsconstants.hrh">
	  <version checksum="BJ4NyJRChv9Aq">
      <status>OK</status>
      <comment>Enum values added without changing any of the existing enum values.</comment>
    </version>
	  <version checksum="68Z+J7RChv9Aq">
      <status>OK</status>
      <comment>Enum values added without changing any of the existing enum values.</comment>
    </version>
	  <version checksum="wC2PLzbChv9Aq">
      <status>OK</status>
      <comment>Enum values added without changing any of the existing enum values.</comment>
    </version>
    <version checksum="o0yoK2MChv9Aq">
      <status>OK</status>
      <comment>Enum values added without changing any of the existing enum values.</comment>
    </version>
    <version checksum="8A7CQzEChv9Aq">
      <status>OK</status>
      <comment>Enum values added without changing any of the existing enum values.</comment>
    </version>
    <version checksum="0155tuSChv9Aq">
      <status>OK</status>
      <comment>Enum values added without changing any of the existing enum values.</comment>
    </version>
    <version checksum="25Fe53BChv9Aq">
      <status>OK</status>
      <comment>Enum values added without changing any of the existing enum values.</comment>
    </version>
    <version checksum="flMwFF-Chv9Aq">
      <status>OK</status>
      <comment>Enum values added without changing any of the existing enum values.</comment>
    </version>
    <version checksum="flMwFF-Chv9Aq">
      <status>OK</status>
      <comment>Enum values added without changing any of the existing enum values.</comment>
    </version>
    <version checksum="IdcDcyuChv9Aq">
      <status>OK</status>
      <comment>Enum values added without changing any of the existing enum values.</comment>
    </version>
    <version checksum="cxeqsI7Chv9Aq">
      <status>OK</status>
      <comment>Enum values added without changing any of the existing enum values.</comment>
    </version>
     <version checksum="EMu33UcChv9Aq">
      <status>OK</status>
      <comment>Enum values added without changing any of the existing enum values.</comment>
    </version>
    <version checksum="3L5Op3zChv9Aq">
      <status>OK</status>
      <comment>Enum values added without changing any of the existing enum values.</comment>
    </version>
    <version checksum="hyqaQM7Chv9Aq">
      <status>OK</status>
      <comment>Enum values added without changing any of the existing enum values.</comment>
    </version>
    <version checksum="6OTS6UnChv9Aq">
      <status>OK</status>
      <comment>Enum values added without changing any of the existing enum values.</comment>
    </version>
    <version checksum="AXGK0RcChv9Aq">
      <status>OK</status>
      <comment>Enum values added without changing any of the existing enum values.</comment>
    </version>
    <version checksum="kEvgmkNChv9Aq">
      <status>OK</status>
      <comment>Enum values added without changing any of the existing enum values.</comment>
    </version>
    <version checksum="L93HT6dChv9Aq">
      <status>OK</status>
      <comment>Enum values added without changing any of the existing enum values.</comment>
    </version>
    <version checksum="lzzRl+pBFXFou">
      <status>OK</status>
      <comment>Guard macro changed. It's ok </comment>
    </version>
	</headerfile>
 
	<headerfile name="mw\aknsconstants.hrh">
    <version checksum="+BLxL4iChv9Aq">
      <status>OK</status>
      <comment>Enum values added without changing any of the existing enum values.</comment>
    </version>
    <version checksum="+BLxL4iBxn4WA">
      <status>OK</status>
      <comment>Enum values added without changing any of the existing enum values.</comment>
    </version>
    <version checksum="AYopK8cBs74HL">
      <status>OK</status>
      <comment>Enum values added without changing any of the existing enum values.</comment>
    </version> 
    <version checksum="7Y-sjk5Bxn4WA">
      <status>OK</status>
      <comment>Enum values added without changing any of the existing enum values.</comment>
    </version>
    <version checksum="vsjqRpGDHADQH">
      <status>OK</status>
      <comment>Enum values added(to TAknsMinorGenericValue) without changing any of the existing enum values.Enum member (of TAknsMinorSkinValue) name changed,it is not a bc break.</comment>
    </version>
    <version checksum="OFCo3cCDHADQH">
      <status>OK</status>
      <comment>Enum values added(to TAknsMinorGenericValue) without changing any of the existing enum values.Enum member (of TAknsMinorSkinValue) name changed,it is not a bc break.</comment>
    </version>
    <version checksum="t+IdBg0Chv9Aq">
      <status>OK</status>
      <comment>Enum values added(to TAknsMinorGenericValue) without changing any of the existing enum values.</comment>
    </version>
    <version checksum="btTMwPwChv9Aq">
      <status>OK</status>
      <comment>Enum values added(to TAknsMinorGenericValue) without changing any of the existing enum values.</comment>
    </version>
    <version checksum="49vG08FChv9Aq">
      <status>OK</status>
      <comment>Enum values added without changing any of the existing enum values.</comment>
    </version>
    <version checksum="fXbxDR0Chv9Aq">
      <status>OK</status>
      <comment>Enum values added without changing any of the existing enum values.</comment>
    </version>
    <version checksum="CSsD5okChv9Aq">
      <status>OK</status>
      <comment>Enum values added without changing any of the existing enum values.</comment>
    </version>
   </headerfile>
	
	 <headerfile name="middleware\aknsconstants.h">
    <version checksum="I4GXbo1Bs74HL">
      <status>OK</status>
      <comment>All are depreciated constants, and changing the name of it is ok.</comment>
    </version>
    <version checksum="QQi74jHBs74HL">
      <status>OK</status>
      <comment>All are depreciated constants, and changing the name of it is ok.</comment>
    </version>
    <version checksum="AYopK8cBs74HL">
      <status>OK</status>
      <comment>All are depreciated constants, and changing the name of it is ok.</comment>
    </version>
    <version checksum="SClzbOFBs74HL">
      <status>OK</status>
      <comment>All are depreciated constants, and changing the name of it is ok.</comment>
    </version>
    <version checksum="C5FXvW8Bs74HL">
      <status>OK</status>
      <comment>All are depreciated constants, and changing the name of it is ok.</comment>
    </version>
          
   </headerfile>
   
   <headerfile name="mw\aknsconstants.h">
    <version checksum="QQi74jHBs74HL">
      <status>OK</status>
      <comment>All are depreciated constants, and changing the name of it is ok.</comment>
    </version>  
    <version checksum="AYopK8cBs74HL">
      <status>OK</status>
      <comment>All are depreciated constants, and changing the name of it is ok.</comment>
    </version>
    <version checksum="C5FXvW8Bs74HL">
      <status>OK</status>
      <comment>All are depreciated constants, and changing the name of it is ok.</comment>
    </version>  
   </headerfile>
   
   <headerfile name="middleware\aknPopupHeadingPane.h">
    <version checksum="RWWnVfsAXbN44">
      <status>NOK</status>
      <comment>CAknPopupHeadingPane is publised class, so changing the size of class is not allowed since constructor is a public member and thus it is derivable.</comment>
    </version>
   </headerfile>

	<headerfile name="middleware\aknsconstants.hrh">
	  <version checksum="zSurkqfChv9Aq">
      <status>OK</status>
      <comment>Only the enum indicating the max value has changed.</comment>
    </version>
	  <version checksum="IWOPeooChv9Aq">
      <status>OK</status>
      <comment>Only the enum indicating the max value has changed.</comment>
    </version>
	  <version checksum="xZZj1sRChv9Aq">
      <status>OK</status>
      <comment>Only the enum indicating the max value has changed.</comment>
    </version>
	  <version checksum="Cwn9JKEChv9Aq">
      <status>OK</status>
      <comment>Only the enum indicating the max value has changed.</comment>
    </version>
	 <version checksum="ezMN5m3Chv9Aq">
      <status>OK</status>
      <comment>Only the enum indicating the max value has changed.</comment>
    </version>
    <version checksum="IdcDcyuChv9Aq">
      <status>OK</status>
      <comment>Enum values added without changing any of the existing enum values.</comment>
    </version>
    <version checksum="88goBx8Chv9Aq">
      <status>OK</status>
      <comment>Enum values added without changing any of the existing enum values.</comment>
    </version>
    <version checksum="cxeqsI7Chv9Aq">
      <status>OK</status>
      <comment>Enum values added without changing any of the existing enum values.</comment>
    </version>
    <version checksum="IPKfCxcChv9Aq">
      <status>OK</status>
      <comment>Enum values added without changing any of the existing enum values.</comment>
    </version>
    <version checksum="EMu33UcChv9Aq">
      <status>OK</status>
      <comment>Enum values added without changing any of the existing enum values.</comment>
    </version>
    <version checksum="OEsMflbChv9Aq">
      <status>OK</status>
      <comment>Enum values added without changing any of the existing enum values.</comment>
    </version>
    <version checksum="cwbO4hVChv9Aq">
      <status>OK</status>
      <comment>Only the enum indicating the max value has changed.</comment>
    </version>
    <version checksum="3L5Op3zChv9Aq">
      <status>OK</status>
      <comment>Only the enum indicating the max value has changed.</comment>
    </version>
    <version checksum="9UTg2VMChv9Aq">
      <status>OK</status>
      <comment>Only the enum indicating the max value has changed.</comment>
    </version>
    <version checksum="qJvl0tqChv9Aq">
      <status>OK</status>
      <comment>Only the enum indicating the max value has changed.</comment>
    </version>
     <version checksum="I-Y8-plChv9Aq">
      <status>OK</status>
      <comment>Only the enum indicating the max value has changed.</comment>
    </version>
    <version checksum="eSzryquChv9Aq">
      <status>OK</status>
      <comment>Only the enum indicating the max value has changed.</comment>
    </version>
     <version checksum="rHFrlSbChv9Aq">
      <status>OK</status>
      <comment>Only the enum indicating the max value has changed.</comment>
    </version>
    <version checksum="3M-14RgChv9Aq">
      <status>OK</status>
      <comment>Only the enum indicating the max value has changed.</comment>
    </version>
	<version checksum="CFvxeSqChv9Aq">
      <status>OK</status>
      <comment>Only the enum indicating the max value has changed.</comment>
    </version>
    <version checksum="QpDHEkPChv9Aq">
      <status>OK</status>
      <comment>Only the enum indicating the max value has changed.</comment>
    </version>
    <version checksum="hydhFjSChv9Aq">
      <status>OK</status>
      <comment>Only the enum indicating the max value has changed.</comment>
    </version>
    <version checksum="2eL2wwtChv9Aq">
      <status>OK</status>
      <comment>Only the enum indicating the max value has changed.</comment>
    </version>
    <version checksum="CJ2JtmTChv9Aq">
      <status>OK</status>
      <comment>Only the enum indicating the max value has changed.</comment>
    </version>
    <version checksum="qzwK19UChv9Aq">
      <status>OK</status>
      <comment>Only the enum indicating the max value has changed.</comment>
    </version>
    <version checksum="KN1Hl-qChv9Aq">
      <status>OK</status>